### ISSUE TITLE
Database without Primary Key not supported?

### ISSUE THREAD

**Issue by melvinchia** [morris/lessql#20]
I'm trying out lessql but every time I try to use it on a table without Primary Key (I work with some MSSQL databases, and even information_schema.tables in MYSQL does not have a Primary Key, it gives me an error:

`PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in xxxxxx`

There's no Primary Key in the table, and I can't add one to it, period. I've tried to assign some of the other columns using $db->setPrimary but it still doesn't work. Does this mean lessql is useless for _all tables_ without a Primary Key?

**Comment by morris** [comment]
May I see your code? LessQL should not require the primary key unless you're querying by primary key or trying to find referenced rows. In any case, setPrimary should work as expected.

**Comment by melvinchia** [comment]
Code is as below:

The pdo equivalent of the code runs fine, the LessQL version bombs with an error (screenshot attached).
![screen shot 2016-07-05 at 10 17 46 am](https://cloud.githubusercontent.com/assets/2408261/16572303/cb32c19a-4299-11e6-8991-7fb0e0ea0cf7.png)

```
<?
$autoloader = require __DIR__ . '/vendor/autoload.php';

$pdo = new PDO('mysql:host=127.0.0.1;dbname=test','root','root');
$pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_OBJ);

$query = 'SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_SCHEMA = "test"';
$data = $pdo->query($query)->fetchAll();
var_dump($data);

$pdo = new PDO('mysql:host=127.0.0.1;dbname=information_schema','root','root');
$pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_OBJ);
$conn = new LessQL\Database($pdo);

$data2 = $conn->table('TABLES')->select('TABLE_NAME')->where('TABLE_SCHEMA', 'test')->fetchAll();
var_dump($data2);

```

**Comment by melvinchia** [comment]
Oops clicked on the wrong button..

**Comment by melvinchia** [comment]
The above code doesn't work even when I change it to:

`$data2 = $conn->table('TABLES')->setPrimary('TABLE_NAME')->select('TABLE_NAME')->where('TABLE_SCHEMA', 'test')->fetchAll();
var_dump($data2);
`

Or:

`$data2 = $conn->setPrimary('TABLE_NAME')->table('TABLES')->select('TABLE_NAME')->where('TABLE_SCHEMA', 'test')->fetchAll();
var_dump($data2);
`

**Comment by morris** [comment]
I see - the setPrimary call should look like "$db->setPrimary( 'TABLES', 'TABLE_NAME' );". The setting is permanent and will be used for subsequent queries. Unfortunately there's probably no error that your usage of setPrimary is invalid.

**Comment by melvinchia** [comment]
Umm, whether setPrimary or not, I'm still unable to pull out the list of tables in a table without an "id" field. This also means that I would not be able to use lessql on MsSQL and SyBase databases although I can pull them in using PDO.. Is there a workaround?

**Comment by morris** [comment]
Here's what i just did:

``` sql
CREATE TABLE TABLES (
    TABLE_NAME varchar(30) NOT NULL,
    TABLE_SCHEMA varchar(30) NOT NULL
)
```

and then

``` php
$db->setPrimary( 'TABLES', 'TABLE_NAME' );
$data = $db->table( 'TABLES' )
  ->select( 'TABLE_NAME' )
  ->where( 'TABLE_SCHEMA', 'test' )
  ->fetchAll();

$this->assertEquals( $data[ 0 ][ 'TABLE_NAME' ], 'testname' );
```

which works. You have to use `setPrimary( $table, $column )`.

**Comment by melvinchia** [comment]
Hi Morris,
Actually you DO have the table in question to play around with. It comes with your stock MYSQL database, and it doesn't have id as an index..

Maybe you could try running it on your MYSQL and see if it works on yours? It didn't work (although the PDO version works) on mine..

**Comment by morris** [comment]
LessQL does not care where that table is, really. You only have to configure the primary key. This works:

``` php
$pdo = new \PDO( 'mysql:host=localhost;dbname=information_schema', 'root' );
$db = new \LessQL\Database( $pdo );

$db->setPrimary( 'TABLES', 'TABLE_NAME' );

$data = $db->table( 'TABLES' )
    ->select( 'TABLE_NAME' )
    ->where( 'TABLE_SCHEMA', 'test' )
    ->fetchAll();
```

You must have some mistake in your code.
