### ISSUE TITLE
Where column LIKE queries

### ISSUE THREAD

**Issue by gausam** [morris/lessql#22]
How can I do _WHERE ... LIKE_ queries with LessQL (if that's possible)? Nothing on those in the docs

**Comment by Langmans** [comment]
You can use [`LessQL\Literal`](https://github.com/morris/lessql/blob/v0.3.4/src/LessQL/Literal.php).

A [facade method](https://sourcemaking.com/design_patterns/facade/php)  `whereLiteral` or `whereLike` would be nice I suppose.

**Comment by gausam** [comment]
:+1:  Thanks, will try that route. Had fallen back to pure PDO for that.

**Comment by morris** [comment]
->where( 'col LIKE ?', array( '%foo%' ) ) should work too

**Comment by gausam** [comment]
Nice. I'd only quickly tried ->where('col', 'LIKE %foo') which of course didn't work. Will let you know how I fare.

**Comment by gausam** [comment]
@morris Hmm how would I go about expressing this in LessQL:

`'SELECT * FROM lorem WHERE (ipsum= ? OR ipsum LIKE ?)`

The real question I wanted to ask though (without opening a new issues) is how can I make LessQL to update the `updated_at` column every time I call save() or update(). I know I can go in and modify the source code to do that, but maybe there's a way to do it with what's there already.

**Comment by morris** [comment]
The same as above with multiple params.

For an automatic updated_at in v0 you'd have to subclass at least the Database and override update(). v1 will introduce events to enable that use case.

**Comment by gausam** [comment]
Ah I see what you mean, I thought LessQL's `where()` was very strict (Laravel's query builder doesn't tolerate hackery).

Thanks. I think I'll implement some of the things I need in a fork and await the glorious v1, or if I'm confident enough with my understanding of the code base I'll send in a few PRs.

Thanks for all the help Morris
