### ISSUE TITLE
Can you write a better example for Finding and Traversal?

### ISSUE THREAD

**Issue by marcelloh** [morris/lessql#30]
In this example, you render the inbetween results, but in modern frameworks, you first collect the data, and then hand over all the necessary data to a template engine to render the (end) result.

So the following steps will be visible:
get posts and their users and the corresponding categories
call a rendering routine

I was figuring out myself how to do it, but perhaps there is a better way.
My steps in pseudo-code:
create array $allRecords
get all postsRecords
loop over $postsRecords
per $postRecord,
- get corresponding user
- add the $userRecord to the $postsRecord
- get the corresponding $categoryRecords
- add the $categoryRecords to the $postsRecord
- put the modified $postRecord into the $allRecords
endloop

renderthis($allRecords)

**Comment by ilsenem** [comment]
You could either use method that you described, to store all data in the single structure manually, while iterating over results, or use something like [Fractal](https://github.com/thephpleague/fractal) to serialize data passing root element to first serializer and then use it as in `for` loop.

P.S. You should carefully log resulting queries to see if there is no `N+1` problem.
