### ISSUE TITLE
Example on how to get the real sql that Lessql uses to do the queries

### ISSUE THREAD

**Issue by marcelloh** [morris/lessql#31]
In the Finding and Traversal, you end with the first example with 4 queries.
I would like to see what code I must use to see if my example has the expected sql queries.

**Comment by ilsenem** [comment]
Use query logging:

```php
$db->setQueryCallback( function( $query, $params ) use ($logger) {
    $logger->debug('SQL Query: ' . $query, $params); // Assumed we use PSR logger
} );
```

**Comment by mortenn** [comment]
This seems to have been answered, so I suggest closing the issue ^_^

**Comment by goldingdamien** [comment]
@ilsenem Is there a way to get the query SQL up to that point?
For example:
$sql = $db->table('table')
->where("column1", 1)
->whereNot("column2", 2)
->getSQL();

**Comment by Langmans** [comment]
Result->getDefinition outputs the different parts in the query as json.

**Comment by goldingdamien** [comment]
@rubenvincenten Thanks
