### ISSUE TITLE
how to orderby mutliple columns

### ISSUE THREAD

**Issue by marcelloh** [morris/lessql#32]
I have this code:
```
$dataRecords = $db->my_table()
                ->orderBy(['name' => 'ASC', 'age' => 'DESC']);
```
But I got a complain from the quoteIdentifier method, because the identifier must be a string.

I tried, but this fails also:
```
$dataRecords = $db->my_table()
                ->orderBy(['name, ASC']);
```
Any hints are welcome

**Comment by Langmans** [comment]
Result->orderBy() appends to an array, Database->getSuffix() makes a sql partial with it:

https://github.com/morris/lessql/blob/master/src/LessQL/Result.php#L603
https://github.com/morris/lessql/blob/master/src/LessQL/Database.php#L820
```php
$dataRecords = $db->my_table()->orderBy('name', 'ASC')->orderBy('age','DESC')
```

**Comment by marcelloh** [comment]
ok. totally not what I expected, but now that I know, I can work with that :-)
Thanks
