### ISSUE TITLE
add field to row in select query

### ISSUE THREAD

**Issue by marcelloh** [morris/lessql#33]
I don't know how to do this, but sometimes I have to add a field to the row.

Like:
DATE_FORMAT(mydatefield,'%Y%m%d%k%i%S') as mydatefield_sformat

**Comment by Langmans** [comment]
I think you can use the Literal Object, from the top of my head i'm not sure about the correct call but it should be something like this? table (or __call) returns a Result object, where Database joins the expressions (implode) with a comma.

```php
$result = $db->table('post')->select(new LessQL\Literal('DATE_FORMAT(mydatefield,'%Y%m%d%k%i%S') as mydatefield_sformat'))
```
