### ISSUE TITLE
Multiple row insert best practice

### ISSUE THREAD

**Issue by royhg** [morris/lessql#35]
Hi Morris,
Tell me how multiple insert row in array should be defined?
$row1=[0=>[field1,$field2,$field3],1=>[field1,$field2,$field3]];
$row2=[[field1,$field2,$field3],[field1,$field2,$field3]];
$db->table('tableName')->insert($row1/$row2?,'batch')->save();

Regards,
Roy

**Comment by cos800** [comment]
Is there any difference?

**Comment by mortenn** [comment]
As the sample code is run, `$row1` and `$row2` will be identical, so there is no runtime difference.
I would argue that adding the indices is entirely unnecessarily and only serve to add noise to the code.
On the other hand, I would argue for splitting that code up over multiple lines:

    $row1 = [
      [$field1, $field2, $field3],
      [$field1, $field2, $field3]
    ];
