### ISSUE TITLE
Additional PSR compliance?

### ISSUE THREAD

**Issue by shadowhand** [morris/lessql#4]
Any particular reason that LessQL doesn't implement PSR-2 or PSR-4? And how come there are no visibility controls?

**Comment by morris** [comment]
I'm not happy with PSR-2, that's just a matter of taste, but I'd be open to conform if the demand is high enough. I'm unsure if LessQL already complies with PSR-4 - what's missing?

There's just a few protected functions, since public is the default in PHP. Some methods might be better off hidden, but I don't see a benefit right now - however I'm def open for suggestions here, too.

**Comment by harikt** [comment]
:+1: for psr-2 . But if you prefer it, I don't want to force you also. It is a matter of preference. 

The only thing why I like is consistency in every where I write code. open-source to proprietary .

Just my input as you mentioned.

> but I'd be open to conform if the demand is high enough

**Comment by shadowhand** [comment]
It does not [currently use PSR-4](https://github.com/morris/lessql/blob/4f77aab1e9826b4e998c237c44632e17225b158f/composer.json#L15-L17). I don't anything other than a composer config change is necessary.

**Comment by shadowhand** [comment]
The point of code standards is that it's a standard. There are things I don't love about PSR-2 either, but having a standard is better than having none.

**Comment by nataliawinter** [comment]
Hi, it's been 3 years of this discussion, by any chance you consider PSR-2 now? If yes, can I adjust. 😄

**Comment by morris** [comment]
@nataliawinter, A PR is welcome :) ideally with a composer command to autoformat with php-cs-fixer or something?

**Comment by nataliawinter** [comment]
Yay 😄 ! Yes, I'm thinking in use. I will fork the repository and create a pull request 👍

**Comment by nataliawinter** [comment]
Just for information, the PR #50 was the changed about this conversation
