### ISSUE TITLE
Delete returns error when nothing is to be deleted by an "association result"

### ISSUE THREAD

**Issue by allysson-david** [morris/lessql#45]
Consider the following code:
`$db->myTable($id)->anotherTableList()->where($column, $value)->delete();`

If `$db->myTable($id)->anotherTableList()->where($column, $value)` returns nothing `->delete()` will then build a DELETE SQL with an empty WHERE clause.

Result.php line 444 returns true and line 446 is executed.
Result.php line 466 runs the basic query and finds no results (which means nothing should be deleted), but when the code goes on running it skips the loop at 469 (because no rows where found) and runs `return $result->where( implode( " OR ", $or ) );` at 483, but since `$or` is empty it produces `DELETE FROM anotherTable WHERE` which throws an exception.

I guess a very simple workaround would be to add `if(empty($or)) $or[] = "0=1";` at line 482, or 'inherit' its where info from the association result, or even skip the delete procedure altogether.

**Comment by morris** [comment]
Good catch. Care to add a PR with a small test :)? I'll merge happily.
