### ISSUE TITLE
Float numbers are cut when saving into database

### ISSUE THREAD

**Issue by jacekbarecki** [morris/lessql#46]
Steps to reproduce:
1.Execute `$row->update(['number' => 0.00003569]);`
2.The actual value saved in the database is 0.000036, not 0.00003569

This is because of using `sprintf( "%F", $value )` in `\LessQL\Database::quote()`

**Comment by Langmans** [comment]
This isn't really LessQL's fault, but rather PHP's. Two ways to circumvent: 

1. Cast it to a string with strval or a simple (string) (PDO->quote will handle the quoting).
2. Wrap it in a LessQL\Literal.
