### ISSUE TITLE
LogicException: Cannot set Row "clean" without id in C:\xampp\htdocs\vendor\morris\lessql\src\LessQL\Row.php:558

### ISSUE THREAD

**Issue by goldingdamien** [morris/lessql#49]
What causes the error in the title and how to fix?
Regards

**Comment by f0ma** [comment]
There is look like LessQL cannot detect table primary key (column `id` by default). You can set name of primary key column by

`$db->setPrimary( $table, $column );`

**Comment by baselbj** [comment]
I am facing the same issue while using select... in execute function you call the setClean() for each row.

in select we mainly returns a subset of columns and we may not need to return the id of the table.
