### ISSUE TITLE
Support for composite primary keys?

### ISSUE THREAD

**Issue by shadowhand** [morris/lessql#5]
Based on [this code](https://github.com/morris/lessql/blob/7ff03faa4c72cff9fe2a9ee996a4275e551d9fe2/src/LessQL/Database.php#L63) it looks like LessQL does not have any support for composite primary keys. Is this something you've considered adding?

**Comment by morris** [comment]
Yes, there is definitely support for composite primary keys. That snippet just allows the following shorthand: `$db->post( 3 )` which fetches the post with primary key "3". Equivalent would be `$db->post( array( 'id' => 3 ) )`. For composite primary keys, you'll have to use an array anyway, so something like `$db->categorization( array( 'category_id' => 5, 'post_id' => 3 ) )` works.
