### ISSUE TITLE
Between condition

### ISSUE THREAD

**Issue by peignenappe** [morris/lessql#52]
hi there,

I would like to know if there is a way to set a BETWEEN condition when using where() function ?
I tried to use limit(), but its not precise enough..

Maybe someone already found a solution ?
Thanks

**Comment by f0ma** [comment]
Method `where` allows to make expression with `BETWEEN`:

`$between = $db->table('post')->where('id BETWEEN ? AND ?', 0, 100);`

**Comment by peignenappe** [comment]
Oh great, so it's just that simple ! I didn't even tried it, because not explained in the docs.
Thank you so much ! :)
